name: Kotlin CI

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
   gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build

  #  steps:
  #   - uses: actions/checkout@v2
  #    - name: Set up JDK 11
  #      uses: actions/setup-java@v1
  #      with:
  #        java-version: '11'
  #    - name: Run chmod to make gradlew executable
  #      run: chmod +x ./gradlew    
  #    - name: Cache Gradle packages
  #      uses: actions/cache@v1
  #      with:
  #        path: ~/.gradle/caches
  #        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
  #        restore-keys: ${{ runner.os }}-gradle
  #    - name: KTlint check
  #      run: ./gradlew ktlintCheck
